### ISSUE TITLE
保存图片

### ISSUE THREAD

**Issue by Wxianpeng** [typer9527/FaceDetectDemo#3]
如何将绿色的人脸框中的 人脸图片保存下来！

**Comment by typer9527** [comment]
在`public Mat onCameraFrame(CvCameraViewFrame inputFrame)`中，可以将矩阵转为bitmap, 具体可以参考https://github.com/typer9527/FaceDetector/blob/master/app/src/main/java/com/yl/facedetector/activity/DetectActivity.java
